INSERT INTO product (id, name, variety) VALUES (1, 'Emperador', 'Nacional');
INSERT INTO product (id, name, variety) VALUES (2, 'Salmón', null);
INSERT INTO product (id, name, variety) VALUES (3, 'Bonito', 'Del Norte');
INSERT INTO product (id, name, variety) VALUES (4, 'Cazón', null);
INSERT INTO product (id, name, variety) VALUES (5, 'Dorada', 'Nacional');
INSERT INTO product (id, name, variety) VALUES (6, 'Bacalao', 'Fresco');
INSERT INTO product (id, name, variety) VALUES (7, 'Lenguado', 'Fresco');
INSERT INTO product (id, name, variety) VALUES (8, 'Cabracho', null);
INSERT INTO product (id, name, variety) VALUES (9, 'Merluza', null);
INSERT INTO product (id, name, variety) VALUES (10, 'Gallo', 'Ración');
INSERT INTO product (id, name, variety) VALUES (11, 'Lubina', '');
INSERT INTO product (id, name, variety) VALUES (12, 'Mero', '');
INSERT INTO product (id, name, variety) VALUES (13, 'Bregas', null);
INSERT INTO product (id, name, variety) VALUES (14, 'Palometa', null);
INSERT INTO product (id, name, variety) VALUES (15, 'Corvina', null);
INSERT INTO product (id, name, variety) VALUES (16, 'Dorada', 'Pequeña');
INSERT INTO product (id, name, variety) VALUES (17, 'Lenguadina', 'Nacional');
INSERT INTO product (id, name, variety) VALUES (18, 'Salmonetes', null);
INSERT INTO product (id, name, variety) VALUES (19, 'Bonito', 'Pequeño');
INSERT INTO product (id, name, variety) VALUES (20, 'Pescadilla', 'De rosca');
INSERT INTO product (id, name, variety) VALUES (21, 'Pescadilla', null);
INSERT INTO product (id, name, variety) VALUES (22, 'Caballa', 'Del Norte');
INSERT INTO product (id, name, variety) VALUES (23, 'Gallos', 'Pequeños');
INSERT INTO product (id, name, variety) VALUES (24, 'Lisa', null);
INSERT INTO product (id, name, variety) VALUES (25, 'Patorras de chado', 'Fresco');
INSERT INTO product (id, name, variety) VALUES (26, 'Lubina', 'Pequeña');
INSERT INTO product (id, name, variety) VALUES (27, 'Acedias', null);
INSERT INTO product (id, name, variety) VALUES (28, 'Brótola', null);
INSERT INTO product (id, name, variety) VALUES (29, 'Chicharro', 'Grande');
INSERT INTO product (id, name, variety) VALUES (30, 'Congrio', 'Abriro');
INSERT INTO product (id, name, variety) VALUES (31, 'Pajel', null);
INSERT INTO product (id, name, variety) VALUES (32, 'Trucha', 'Asalmonada');
INSERT INTO product (id, name, variety) VALUES (33, 'Calamar', 'Fresco');
INSERT INTO product (id, name, variety) VALUES (34, 'Rejos', null);
INSERT INTO product (id, name, variety) VALUES (35, 'Calamar', 'En anillas');
INSERT INTO product (id, name, variety) VALUES (36, 'Rabas', null);
INSERT INTO product (id, name, variety) VALUES (37, 'Sepia', null);
INSERT INTO product (id, name, variety) VALUES (38, 'Bacaladitos', null);
INSERT INTO product (id, name, variety) VALUES (39, 'Boquerón', 'Pequeño');
INSERT INTO product (id, name, variety) VALUES (40, 'Boquerón', 'Gordo');
INSERT INTO product (id, name, variety) VALUES (41, 'Parrocha', null);
INSERT INTO product (id, name, variety) VALUES (42, 'Sardina', 'Grande');
INSERT INTO product (id, name, variety) VALUES (43, 'Volador', null);
INSERT INTO product (id, name, variety) VALUES (44, 'Rape', null);
INSERT INTO product (id, name, variety) VALUES (45, 'Mejillones', 'Gallegos');
INSERT INTO product (id, name, variety) VALUES (46, 'Chirlas', null);
INSERT INTO product (id, name, variety) VALUES (47, 'Chicharro', 'Pequeño');
INSERT INTO product (id, name, variety) VALUES (48, 'Gamba', 'Arrocera');
INSERT INTO product (id, name, variety) VALUES (49, 'Cangrejos', 'De río');
INSERT INTO product (id, name, variety) VALUES (50, 'Gambón', 'Congelado');
INSERT INTO product (id, name, variety) VALUES (51, 'Langostino', 'Crudo');
INSERT INTO product (id, name, variety) VALUES (52, 'Langostino', 'Cocido');
INSERT INTO product (id, name, variety) VALUES (53, 'Gamba', 'Pelada');
INSERT INTO product (id, name, variety) VALUES (54, 'Chipirón', null);
INSERT INTO product (id, name, variety) VALUES (55, 'Chopitos', null);
INSERT INTO product (id, name, variety) VALUES (56, 'Bogavante', null);
